version: '3.8'
services:
  dev-db:
    image: postgres:15
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: whatchagot_dev
    networks:
      - whatchagot
  test-db:
    image: postgres:15
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: test_whatchagot_dev
    networks:
      - whatchagot

networks:
  whatchagot:
